### ISSUE TITLE
apple wallet

### ISSUE THREAD

**Issue by diemwu** [tomavic/cordova-apple-wallet#1]
Hi, how to determine the credit card is exist in wallet

**Comment by tomavic** [comment]
Hi @diemwu , you can check Apple PKPassLibrary docs from [here] (https://developer.apple.com/documentation/passkit/pkpasslibrary?language=objc)

In the next release I will try to apply more advanced features to the plugin native code :)

**Comment by mg** [comment]
Hi, any update on this issue? It is probably only thing missing from this great (THANK YOU) plugin.

**Comment by tomavic** [comment]
Hi @mg 

Hi Mangus

**Comment by tomavic** [comment]
Hi @mg , currently I was busy in some in-house projects. I promise I will update the plugin very soon. Keep updated ;)

**Comment by tomavic** [comment]
@mg @diemwu Plugin has been updated. Check and waiting for your feedback Enjoy!

**Comment by mg** [comment]
We will try this out over the next 2 weeks and let you know, thank you!
