### ISSUE TITLE
Card Addition documentation error

### ISSUE THREAD

**Issue by Emad88** [tomavic/cordova-apple-wallet#12]
The documentation says to pass `primaryAccountNumberSuffix` but the code looks for `primaryAccountSuffix`, so either the docs need to be corrected or the code needs to standardise the variable name since both names are used in different places.

https://github.com/tomavic/cordova-apple-wallet/blob/1029e6cf1b3de0524fb3ba1dd2f5477120301ace/README.md#L156

https://github.com/tomavic/cordova-apple-wallet/blob/1029e6cf1b3de0524fb3ba1dd2f5477120301ace/src/ios/CDVAppleWallet.m#L253

**Comment by tomavic** [comment]
Hi @Emad88 

A new version has been released. Please check the latest changes. Thanks for your interest in our plugin.
