### ISSUE TITLE
completeAddPaymentPass doesn't use ephemeralPublicKey

### ISSUE THREAD

**Issue by Emad88** [tomavic/cordova-apple-wallet#15]
When using ECC ephemeralPublicKey should be passed instead of wrappedKey, but the code is only looking for wrappedKey.

https://github.com/tomavic/cordova-apple-wallet/blob/929caeb8b6c8ec7902ac664ca378d03868ca07db/src/ios/CDVAppleWallet.m#L365-L379

**Comment by tomavic** [comment]
The latest contribution by @faugusztin has assigned new params for encryption scheme. The next version I'll fix this

**Comment by faugusztin** [comment]
I have multiple fixes for various issues, but didn't want to bother you with them until we got approved by Apple. Over next days i am going to provide pull requests for various issues we found.

**Comment by tomavic** [comment]
Sounds great! The most important thing is to schedule the fixes with priority. Please contact me to organize this. Thanks @faugusztin

**Comment by tomavic** [comment]
@Emad88 the mentioned PR has the fix for this issue. Please wait for our next release.
