### ISSUE TITLE
How to format certificateLeaf and certificateSubCA to the CertificateChain

### ISSUE THREAD

**Issue by buleglay** [tomavic/cordova-apple-wallet#2]
Hi @tomavic,

Could you please share a bit more in terms of how to compose a certificate chain (`NSArray<NSData *> *` according to Apple doc https://developer.apple.com/documentation/passkit/pkaddpaymentpassviewcontrollerdelegate/1615915-addpaymentpassviewcontroller?language=objc) after getting response from `AppleWallet.startAddPaymentPass`?

Many thanks,
Sean

**Comment by tomavic** [comment]
Hi @buleglay 

As you can see from Apple documentation. The callbacks delegate method that let the system prompt you for an add payment request, and inform you when a request has succeeded or failed.

The plugin handles calling this method asynchronously when you call the method `AppleWallet.startAddPaymentPass` which accepts an object as param containing the credit/debit card data as mentioned in [docs here](https://github.com/tomavic/cordova-apple-wallet#start-adding-card)

In case of success, this method will return an object contains all certificates needed to be used by your server-side.

**Comment by buleglay** [comment]
Thanks @tomavic for your detailed explanation. 

I actually found the answer after reading through your code and comment.

As our server is asking for a request payload containing an array of certificates, while the returning object from ‘AppleWallet.startAddPaymentPass’ is not in the exact format the server expects. I was not sure how to format the response data object properly before passing it to the server.

But after looking a bit closer in the code, I realise I just need to put both leaf cert and sub cert into an array with the proper order (leaf first and sub second), then passing them to the server to get the encrypted card data.
