### ISSUE TITLE
Nut bug

### ISSUE THREAD

**Issue by glebfeklistov** [tomavic/cordova-apple-wallet#21]
paymentPasses = [passLibaray passesOfType: PKPassTypeSecureElement];

**Comment by tomavic** [comment]
@glebfeklistov Could you please explain more what do you need and what you asking for?

**Comment by faugusztin** [comment]
He is talking about the typo, which was fixed by PR #22 .

**Comment by tomavic** [comment]
Marked as solved at PR #22
