### ISSUE TITLE
Call to get encrypted card data hangs in iOS 12 

### ISSUE THREAD

**Issue by buleglay** [tomavic/cordova-apple-wallet#3]
Hi,

I noticed an issue while testing the Apple Pay Provisioning with the plugin.

With iOS 12, when firing encrypt card data call to the server, the request gets hanged. When I checked the log, the App somehow got suspended as it’s showing AddPaymentPass view and the app was running in background mode.

It’s working all good in iOS 11, the issue only seems to happen in iOS 12.

Just wondering if anyone experience the same issue and whether there’s a way to get around.

**Comment by tomavic** [comment]
Hi @buleglay 
Could you please provide log or a screenshot to make things more clear?

**Comment by buleglay** [comment]
Hi @tomavic,

Please see attached screenshot of logs from console. 

The one highlighted indicates the App is suspended, and all network process are released, which is causing the encryptCardData call fail (the backend returns response but not handled by the App).

<img width="1004" alt="screen shot 2019-02-26 at 10 45 29 am" src="https://user-images.githubusercontent.com/5381083/53376881-fee72080-39b3-11e9-8b34-4d221963da8c.png">

**Comment by tomavic** [comment]
@buleglay Did you solved the issue?
