### ISSUE TITLE
ID problems

### ISSUE THREAD

**Issue by StekolschikovV** [tomavic/cordova-apple-wallet#30]
I need to implement adding a store card to a wallet. After adding, I see multiple ID errors.
 
<img width="1205" alt="Снимок экрана 2020-09-23 в 13 05 10" src="https://user-images.githubusercontent.com/20765515/93999010-f9270c00-fd9d-11ea-86e6-aaf6dfd8dfcd.png">

Application Information:

>MacBook-Pro:aw4 user$ ionic info
Ionic:
   Ionic CLI                     : 6.11.8 (/Users/user/.npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.3
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3
Cordova:
   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 5 other plugins)
Utility:
   cordova-res (update available: 0.15.1) : 0.10.0
   native-run (update available: 1.1.0)   : 0.2.9
System:
   Android SDK Tools : 26.1.1 (/Users/user/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.18.1 (/usr/local/bin/node)
   npm               : 6.14.8
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C505

>MacBook-Pro:aw4 user$ ionic cordova plugin
 cordova plugin ls
cordova-apple-wallet 1.0.0 "AppleWallet"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

Performed the following actions:

1. ionic start testApp
2. ionic cordova plugin add cordova-apple-wallet
3. npm install @ionic-native/apple-wallet
4. add plugin to app.module.ts (providers) and component
5. ionic cordova platform add ios
6. ionic cordova build ios
7. add application id to xcode

Without this plugin, the application starts and runs without errors.

I ask for your help!

**Comment by faugusztin** [comment]
Xcode 11.3.1 includes iOS 13.3 SDK. As you can see from the @available condition above, the block you error at is intended for iOS 13.5, thus the code requires you to have iOS 13.5 SDK. That is in Xcode 11.5, thus you need to either upgrade your Xcode, or manually remove the blocks of code which use iOS 13.5 SDK features.
