### ISSUE TITLE
How to check and add a card correctly?

### ISSUE THREAD

**Issue by StekolschikovV** [tomavic/cordova-apple-wallet#31]
I need to be able to check the availability of the card and, if necessary, add it. I am interested in both dbet cards and QR codes.

Example: 

![IMG_0037](https://user-images.githubusercontent.com/20765515/94119217-431ff880-fe57-11ea-88d5-a9e43ce3294e.PNG)

I try:
```
   this.appleWallet.isAvailable()
            .then((res: boolean) => {
                console.log(res)
            })
            .catch((err) => {
                console.log(err)
            });
```
result: 
`false`

I try:

```
        let data = {
            cardholderName: 'Test User',
            primaryAccountSuffix: '1234',
            localizedDescription: 'Description of payment card',
            paymentNetwork: 'VISA',
            encryptionScheme: 'RSA_V2',
            primaryAccountNumberSuffix: '1234',
        }
        this.appleWallet.startAddPaymentPass(data).then((res) => {
            console.log(res)
        }).catch((err) => {
                console.log(err)
        });
```

result: 
`
"Can not init PKAddPaymentPassViewController"
`

What do I need to do to add an example card and a debit card?

Performed the following actions:

1. ionic start testApp
2. ionic cordova plugin add cordova-apple-wallet
3. npm install @ionic-native/apple-wallet
4. add plugin to app.module.ts (providers) and component
5. use methods isAvailable and startAddPaymentPass
6. ionic cordova platform add ios
7. ionic cordova build ios
8. add application id to xcode

> MacBook-Pro:aw4 user$  ionic info
> 
> Ionic:
> 
>    Ionic CLI                     : 6.11.8 (/Users/user/.npm-global/lib/node_modules/@ionic/cli)
>    Ionic Framework               : @ionic/angular 5.3.3
>    @angular-devkit/build-angular : 0.1000.8
>    @angular-devkit/schematics    : 10.0.8
>    @angular/cli                  : 10.0.8
>    @ionic/angular-toolkit        : 2.3.3
> 
> Cordova:
> 
>    Cordova CLI       : 10.0.0
>    Cordova Platforms : ios 6.1.1
>    Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 5 other plugins)
> 
> Utility:
> 
>    cordova-res (update available: 0.15.1) : 0.10.0
>    native-run (update available: 1.1.0)   : 0.2.9
> 
> System:
> 
>    Android SDK Tools : 26.1.1 (/Users/user/Library/Android/sdk)
>    ios-deploy        : 1.10.0
>    ios-sim           : 8.0.2
>    NodeJS            : v12.18.1 (/usr/local/bin/node)
>    npm               : 6.14.8
>    OS                : macOS Catalina
>    Xcode             : Xcode 12.0 Build version 12A7209

> MacBook-Pro:aw4 user$  ionic cordova plugin
> > cordova plugin ls
> cordova-apple-wallet 1.0.0 "AppleWallet"
> cordova-plugin-device 2.0.2 "Device"
> cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
> cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
> cordova-plugin-splashscreen 5.0.2 "Splashscreen"
> cordova-plugin-statusbar 2.4.2 "StatusBar"
> cordova-plugin-whitelist 1.3.3 "Whitelist"

I ask for your help!

**Comment by tomavic** [comment]
Hey  @StekolschikovV 

Adding payment passes requires a special entitlement issued by Apple. Your app must include this entitlement before you can use this class. For more information on requesting this entitlement.

**Comment by faugusztin** [comment]
Also after Apple gave you the special entitlement to your **production** provisioning profile, you also need to set up your app entitlement file too, see #20 .
Because the entitlement is added to your production provisioning profile, the Wallet API methods work only when ran on TestFlight or actual App Store release, as those are the only places where the production provisioning profile is used.

And finally, you can only see payment entitlements which were provisioned to be seen by your app, you can't see any other cards added to wallet. See [API documentation](https://developer.apple.com/documentation/passkit/pkpasslibrary/1617109-passes):

> Your app only has access to certain passes, based on its entitlements. Passes that your app doesn’t have access to are not returned.

**Comment by tomavic** [comment]
@StekolschikovV Good Luck with that
