### ISSUE TITLE
checkCardEligibilityBySuffix for cards manually added to the wallet

### ISSUE THREAD

**Issue by sadyan42** [tomavic/cordova-apple-wallet#32]
Greetings, please tell me. The checkCardEligibilityBySuffix method returns cards that I manually added to the wallet, I didn’t use the add plugin. Now method call with any cardSuffix returns true. I can't figure out what the problem is. Thanks in advance

**Comment by tomavic** [comment]
@sadyan42 Hi

I will investigate and get back to you soon. I appreciate your interest in our plugin.

**Comment by sadyan42** [comment]
I figured out this issue. As written here https://github.com/tomavic/cordova-apple-wallet/issues/25, the issue is most likely related to the reservation information from your card operator. See https://developer.apple.com/forums/thread/109968 (value of associatedApplicationIdentifiers). This parameter is rendered as TeamId.BundleId
