### ISSUE TITLE
Add pass to Apple Wallet

### ISSUE THREAD

**Issue by cuni0716** [tomavic/cordova-apple-wallet#7]
Hi @tomavic !

Is there a way to add a simple pass (not a payment card) to apple wallet? If not, is possible to implement that functionality?

Very thanks for sharing your code!!

**Comment by tomavic** [comment]
Hi @cuni0716 

Yes there is a way but not included in this plugin. You can simply use cordova [cordova-pass-book](https://github.com/passslot/cordova-plugin-passbook) 

My plugin is only for payment passes

**Comment by cuni0716** [comment]
Ok, thanks @tomavic!
