### ISSUE TITLE
Checking if card is already in wallet

### ISSUE THREAD

**Issue by mg** [tomavic/cordova-apple-wallet#8]
Hi,

Before checkCardEligibility and checkCardEligibilityBySuffix landed, the plugin had the method isCardExistInWalletOrWatch(), which we could use to check if the card had already been added to the users wallet. It seems that the eligibility methods do not answer that question. Should we use checkPairedDevicesBySuffix() to check for presence of card in wallet, and if so, what is the point of the eligibility methods?

cheers

**Comment by tomavic** [comment]
@mg The implementation for the old method `isCardExistInWalletOrWatch()` is the same as the method `checkPairedDevicesBySuffix()`.

I am currently working on the next release of the plugin. If you are facing any problem, please let me know in details.

**Comment by tomavic** [comment]
If you have any suggestion regarding the methods names, or even a coding review please let me know :))
