### ISSUE TITLE
Support for PKEncryptionSchemeECC_V2 in startAddPaymentPass call

### ISSUE THREAD

**Issue by faugusztin** [tomavic/cordova-apple-wallet#9]
The [PKEncryptionScheme](https://developer.apple.com/documentation/passkit/pkencryptionscheme?language=objc) type contains two encryption schemes - PKEncryptionSchemeECC_V2 and PKEncryptionSchemeRSA_V2. 
Right now plugin has PKEncryptionSchemeRSA_V2 [hardcoded](https://github.com/tomavic/cordova-apple-wallet/blob/master/src/ios/CDVAppleWallet.m#L228). 
Would it be possible to provide a choice of encryption scheme as a configuration option of the startAddPaymentPass call ?

**Comment by tomavic** [comment]
@faugusztin we need to test this on the new iOS 13

**Comment by faugusztin** [comment]
@tomavic Unfortunately our development process is not yet in a phase that i could test out if it works with the payment system. The code compiles and doesn't throw run-time errors on iOS 13.3.1.

**Comment by tomavic** [comment]
@faugusztin @STtraveller 

A new version has been released. Please check the latest changes. Thanks for your interest in our plugin.

**Comment by tomavic** [comment]
@faugusztin Please check on this issue #15

**Comment by tomavic** [comment]
The fix has been applied #18
